def landuse(CATEGORY): 
  if "1A" in CATEGORY: 
    return "Rural Residential" 
  elif !CATEGORY! == "1B" 
    return "Suburban Residential" 
  elif !CATEGORY! == "1A" 
    return "Urban Residential" 
  elif !CATEGORY! == "2A" 
    return "Community Commercial" 
  elif !CATEGORY! == "3" 
    return "Employment" 
  elif !CATEGORY! == "4" 
    return "Public Facilities" 
  elif !CATEGORY! == "4LS" 
    return "Landfill Site" 
  elif !CATEGORY! == "5" 
    return "Open Space" 
  elif !CATEGORY! == "6" 
    return "Urban Activity Center"
